<a href="https://colab.research.google.com/github/fahmi54321/ml_support_vector_regression/blob/main/evaluasi_support_vector_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Support Vector Regression (SVR)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [2]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [4]:
# convert data y horizontal to data y vertical
# reshape (row,column)
y = y.reshape(len(y),1)

In [5]:
print(y)

[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


## Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
x_train = sc_x.fit_transform(x_train)
y_train = sc_y.fit_transform(y_train)
x_test = sc_x.fit_transform(x_test)
y_test = sc_y.fit_transform(y_test)

In [13]:
print(x_train)

[[-1.13572795 -0.88685592  0.67357894  0.52070558]
 [-0.80630243 -0.00971567  0.45145467  0.14531044]
 [ 1.77128416  1.84743445  0.24279248 -1.88374143]
 ...
 [-0.38409993 -1.24886277  0.84522042  0.13092486]
 [-0.9232821  -1.04155299  1.54693117  0.8830852 ]
 [ 1.70136528  1.05824381 -1.20438076 -2.42285818]]


In [14]:
print(y_train)

[[ 1.15069786]
 [ 0.79540777]
 [-1.30936356]
 ...
 [ 0.27595724]
 [ 0.49346982]
 [-1.53508417]]


In [15]:
print(x_test)

[[ 1.20759979  1.91603539 -0.63952486 -0.29302477]
 [-0.28087689 -0.35310215  1.37869679  0.76546975]
 [-0.62969701 -0.84967461  0.99025246  1.76576762]
 ...
 [-0.97851712 -0.70825077  1.75531891  1.01742705]
 [ 1.02387011 -0.46910147 -1.6697468  -0.96742135]
 [-0.30750438 -1.09994713 -1.0566803   0.06163251]]


In [16]:
print(y_test)

[[-1.36721128]
 [ 0.3156057 ]
 [ 0.38167878]
 ...
 [ 1.0903564 ]
 [-0.97135753]
 [ 0.50680833]]


## Training the SVR model on the whole dataset

In [17]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting the train set results

In [19]:
# reverse the scalling, that we apply to output y
y_pred_train = sc_y.inverse_transform(regressor.predict(sc_x.transform(x_train)).reshape(-1,1))
np.set_printoptions(precision = 2)
y_pred_train_reshape = y_pred_train.reshape(len(y_pred_train),1) # convert dari tampilan horizontal ke vertikal
y_train_reshape = y_train.reshape(len(y_train),1) # convert dari tampilan horizontal ke vertikal
print(np.concatenate((y_pred_train_reshape,y_train_reshape), 1))


[[ 1.23  1.15]
 [ 0.65  0.8 ]
 [-1.41 -1.31]
 ...
 [ 0.45  0.28]
 [ 0.87  0.49]
 [-1.38 -1.54]]


## Predicting the test set results

In [20]:
# reverse the scalling, that we apply to output y
y_pred_test = sc_y.inverse_transform(regressor.predict(sc_x.transform(x_test)).reshape(-1,1))
np.set_printoptions(precision = 2)
y_pred_test_reshape = y_pred_test.reshape(len(y_pred_test),1) # convert dari tampilan horizontal ke vertikal
y_test_reshape = y_test.reshape(len(y_test),1) # convert dari tampilan horizontal ke vertikal
print(np.concatenate((y_pred_test_reshape,y_test_reshape), 1))


[[-1.16 -1.37]
 [ 0.2   0.32]
 [ 0.38  0.38]
 ...
 [ 0.93  1.09]
 [-0.88 -0.97]
 [ 0.36  0.51]]


## Evaluating the Model Training Set Performance

In [21]:
from sklearn.metrics import r2_score
r2_score(y_train, y_pred_train)

0.9451854387167586

## Evaluating the Model Test Set Performance

In [22]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_test)

0.9482206410200288